### ISSUE TITLE
Gitter channel?

### ISSUE THREAD

**Issue by bollu** [grin-tech/grin#8]
It would be very cool if there was a gitter channel to discuss things in general about `GRIN`. I would love to have discussions about the general direction of the project, etc.Please consider creating a channel!

**Comment by csabahruska** [comment]
Hi,
Please join to our gitter channel:
https://gitter.im/Grin-Development/Lobby

I'd love to have discussions about `GRIN` and related ideas.

**Comment by bollu** [comment]
Thanks! I sent a PR to make the gitter channel more visible (https://github.com/grin-tech/grin/pull/9).
